### ISSUE TITLE
VOMS users in multiple tenants

### ISSUE THREAD

**Issue by enolfc** [IFCA/keystone-voms#12]
VOMS users are supposed to be included in a single tenant corresponding to the VO of the proxy
Current implementation adds tenants to users as they authenticate so when using a unscoped token, Keystone will return as many tenants as VOs the user belongs to and has tried to authenticate to.

**Comment by alvarolopez** [comment]
Solved in commit 8ca947e56f3662d3bf910196bb711661d0458859.
