### ISSUE TITLE
The keystone-voms module fails when the hash start with '0'

### ISSUE THREAD

**Issue by Pansanel** [IFCA/keystone-voms#43]
Using the last version of the keystone-voms module, I get the following error:
ERROR keystone.common.wsgi FileError: Cannot load file /etc/grid-security/certificates/e635db3.0: [Errno 2] No such file or directory: '/etc/grid-security/certificates/e635db3.0'

The functions computing the hash:
https://github.com/IFCA/keystone-voms/blob/stable/mitaka/keystone_voms/voms.py#L128
https://github.com/IFCA/keystone-voms/blob/stable/mitaka/keystone_voms/voms.py#L142
https://github.com/IFCA/keystone-voms/blob/stable/mitaka/keystone_voms/voms.py#L146
are removing the '0' in front of the hash.

The hash should be 0e635db3:
```
openssl x509 -noout -hash < /etc/grid-security/certificates/SRCE.pem
0e635db3
```

**Comment by alvarolopez** [comment]
Hi Jerome, thanks for the issue and the change.

This was already fixed and released, although I forgot to merge back the changes here (done in #45  and #46).

However, I do think that your solution is simpler (i.e. changing the string formatting). Would you mind to redo your change and make a pull request against the master branch?
